name: Create EC2

on:
  push:
    branches: [ "main" ]
  repository_dispatch:
    types: [deploy-infra]

jobs:
  deploy-ec2:
    runs-on: ubuntu-latest

    env:
      STACK_NAME: dev-ec2-stack
      #REGION: us-east-1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_REGION }}

      - name: Deploy EC2 using CloudFormation
        run: |
          aws cloudformation deploy \
            --template-file simple-ec2.yml \
            --stack-name $STACK_NAME \
            --parameter-overrides KeyName=your-key-name \
            --capabilities CAPABILITY_NAMED_IAM
