name: Deploy Simple EC2 with CloudFormation

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [deploy-infra]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      STACK_NAME: simple-ec2-stack
      TEMPLATE_FILE: simple-ec2.yml
      # REGION: us-east-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --stack-name $STACK_NAME \
            --template-file $TEMPLATE_FILE \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Get stack outputs
        run: |
          aws cloudformation describe-stacks \
            --stack-name $STACK_NAME \
            --query "Stacks[0].Outputs"
