name: Main Infra Workflow

on:
  workflow_dispatch:

jobs:
  trigger-frontend-build:
    uses: ./.github/workflows/reusable.yml@main
    with:
      frontend_repo: MgsParthiban/Front-end-repo
      branch: main
    secrets:
      REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
