name: Main Infra Workflow

on:
  workflow_dispatch:

jobs:
  trigger-frontend-build:
    uses: ./.github/workflows/reusable.yml
    with:
      frontend_repo: myy-org/Front-end-repo
      front_branch: main
      backend_repo: myy-org/application-repo
      back_branch: dev
      
    secrets:
      REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
